name: Deploy to Oracle Linux via SSH

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to the main branch

jobs:
  deploy:
    runs-on: oraclelinux-8.6  # Use Oracle Linux 8.6 as the runner

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up SSH agent and add the private key
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 3: Deploy to the Oracle Linux instance
      - name: Deploy to Oracle Linux
        run: |
          ssh -o StrictHostKeyChecking=no opc@${{ secrets.SERVER_IP }} "bash -c 'cd /path/to/your/app && git pull origin main && npm install && npm run build && pm2 restart all'"
"
